export const dataCreateForm = [
  {
    type: "text",
    attr: "account",
    placeholder: "Account...",
    label: "Account",
    pattern: "",
    min: "6",
  },
  {
    type: "text",
    attr: "name",
    placeholder: "Name...",
    label: "Name",
    pattern: "",
    min: "6",
  },
  {
    type: "text",
    attr: "password",
    placeholder: "Password...",
    label: "Password",
    pattern: "",
    min: "6",
  },
  {
    type: "email",
    attr: "email",
    placeholder: "Email...",
    label: "Email",
    pattern: "",
    min: "6",
  },
  {
    type: "text",
    attr: "phone",
    placeholder: "Phone...",
    label: "Phone",
    pattern: "^[0-9]*$",
    min: "8",
  },
  {
    type: "text",
    attr: "idGroup",
    placeholder: "ID Group...",
    label: "ID Group",
    pattern: "",
    min: "4",
  },
];
